-- CREAR TABLESPACE TS_DATA_01 TAMAÑO 100M AUTOESCALABLE DE 20M HASTA 500M
CREATE tablespace ts_data_01
datafile 'C:\app\1140831727\product\18.0.0\oradata\XE\test_01.bdf'
SIZE 100M
AUTOEXTEND ON NEXT 20M
MAXSIZE 500M;

-- ACTIVAR LOS SCRIPTS DE ORACLE
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- CREAR USUARIO
CREATE USER ts_user_01 IDENTIFIED BY root
DEFAULT tablespace ts_data_01;

-- PERMISOS
GRANT CREATE SESSION TO ts_user_01;
GRANT ALL PRIVILEGES TO ts_user_01;

-- CAMBIAMOS AL USUARIO TS_USER_01
-- ALTERNAMOS LA SESION PARA REAFIRMAR EL ESQUEMA SOBRE EL USUARIO
ALTER SESSION SET CURRENT_SCHEMA = ts_user_01;
