-------------------------------------------------------------------------
-- INSERTAR SUCURSALES
INSERT
	INTO SUCURSAL (S_NOMBRE, S_CIUDAD, S_CALLE) 
	VALUES ('NORTE', 'BARRANQUILLA', 'POR AHI');
INSERT 
    INTO SUCURSAL (S_NOMBRE, S_CIUDAD, S_CALLE) 
    VALUES ('CENTRO', 'BARRANQUILLA', 'POR AHI');
INSERT
    INTO SUCURSAL (S_NOMBRE, S_CIUDAD, S_CALLE) 
    VALUES ('SUR', 'BARRANQUILLA', 'POR AHI');
-------------------------------------------------------------------------
-- INSERTAR PRODUCTOS
INSERT 
	INTO PRODUCTO (PROD_NOMBRE, PROD_INTERES)
	VALUES ('CAT', 0.06);
INSERT 
	INTO PRODUCTO (PROD_NOMBRE, PROD_INTERES)
	VALUES ('CATS', 0.08);
INSERT 
	INTO PRODUCTO (PROD_NOMBRE, PROD_INTERES)
	VALUES ('CDT', 0.01);
--------------------------------------------------------------------------
--INSERTAR CLIENTES
INSERT
	INTO CLIENTE (
		S_ID,
		CLIENTE_TDOCUM, 
		CLIENTE_DOCUM, 
		CLIENTE_PNOMBRE, 
		CLIENTE_PAPELLIDO, 
		CLIENTE_SAPELLIDO, 
		CLIENTE_EMAIL, 
		CLIENTE_CIUDAD, 
		CLIENTE_CALLE, 
		CLIENTE_NUMERO
	) 
	values (
		01,
		'CC', 
		1140831727, 
		'ANGEL', 
		'PALMA', 
		'MARTINEZ', 
		'AEPALMA4712@GMAIL.COM', 
		'BARRANQUILLA', 
		'CALLE TAL', 
		3121112223344
	);
INSERT
	INTO CLIENTE (
		S_ID,
		CLIENTE_TDOCUM, 
		CLIENTE_DOCUM, 
		CLIENTE_PNOMBRE, 
		CLIENTE_PAPELLIDO, 
		CLIENTE_SAPELLIDO, 
		CLIENTE_EMAIL, 
		CLIENTE_CIUDAD, 
		CLIENTE_CALLE, 
		CLIENTE_NUMERO
	) 
	values (
		02,
		'CC', 
		1140831728, 
		'ANGELO', 
		'PALMA', 
		'MARTINEZ', 
		'AEPALMA4712@GMAIL.COM', 
		'BARRANQUILLA', 
		'CALLE TAL', 
		3121112223345
	);
--------------------------------------------------------------------
-- INSERSIÓN CUENTAS
INSERT
	INTO CUENTA (
		CLIENTE_ID,
		S_ID,
		PROD_ID,
		CUENTA_NUMERO,
		CUENTA_ESTADO,
		CUENTA_MONTO,
		CUENTA_TIPO,
		CUENTA_FECHA
	) 
	values (
		1,
		1,
		1,
		88819900929, 
		'ACTIVA', 
		3000000, 
		'AHORRO',
		(SELECT CURRENT_TIMESTAMP from dual)
	);